### ISSUE TITLE
[TIP] How to get original images from bandcamp/mixcloud

### ISSUE THREAD

**Issue by ModestDeer8316** [idleberg/get-cover-bookmarklet#1]
by just removing the size from the mixcloud url you can get the original artwork size
![image](https://user-images.githubusercontent.com/45168911/212391122-be6c1b56-064a-49f8-bc03-c5f1c887af5b.png)

Example
https://thumbnailer.mixcloud.com/unsafe/extaudio/c/9/9/3/4081-e376-4e5d-bdbe-fb544a3a4c0b
https://thumbnailer.mixcloud.com/unsafe/900x900/extaudio/c/9/9/3/4081-e376-4e5d-bdbe-fb544a3a4c0b

also with bandcamp you can also get the original artwork size by replacing _10 with _0

Example
https://f4.bcbits.com/img/a3870979841_10.jpg
https://f4.bcbits.com/img/a3870979841_0.jpg

**Comment by idleberg** [comment]
Thanks a lot for these tips, I've updated the bookmarklet to include your suggestions

**Comment by ModestDeer8316** [comment]
Thanks man, can you also include the mixcloud one? tried to do it and it still shows 900x900

**Comment by idleberg** [comment]
I misread the issue and applied both changes to Bandcamp images. Should be fixed now!
